### ISSUE TITLE
Unable to build the clio.sln file in visual studio 19

### ISSUE THREAD

**Issue by NagarajuPetla** [Advance-Technologies-Foundation/clio#110]

**Comment by NagarajuPetla** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	
Unable to find package Common.Logging.NLog45. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	cliogate	D:\Clio\clio-master\cliogate\cliogate.csproj

**Comment by oleksandr-davydko** [comment]
I have removed this obsolete ref, now the project is building correctly. Feel free to close an issue, if you're not experiencing problems with build anymore.
