### ISSUE TITLE
CreatioSDK NuGet package missing

### ISSUE THREAD

**Issue by kirillkrylov** [Advance-Technologies-Foundation/clio#111]
![RestorePackage](https://user-images.githubusercontent.com/7285114/71575683-90ed1780-2af6-11ea-8b90-32f722708c68.png)

Where is **CreatioSDK** NuGet ?

**Comment by alexbondj** [comment]
This package is in Nexus repository. To restore you have to add the creatio nexus repository in the list of your repos. I f you didn't know how to do it? please write to support.
