### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by kirillkrylov** [Advance-Technologies-Foundation/clio#113]
If I accidentally issue wrong command I get  Unhandled Exception

![image](https://user-images.githubusercontent.com/7285114/73062839-02c24200-3ea6-11ea-879d-28b756325f61.png)

**Comment by alexbondj** [comment]
I can't reproduce.  Can you give me exact case? 
when I type "clio ping help" I've got error "Invalid URI: The format of the URI could not be determined" and it is correct.
