### ISSUE TITLE
Unhanded Exception when appsettings.json is empty is empty

### ISSUE THREAD

**Issue by kirillkrylov** [Advance-Technologies-Foundation/clio#114]
if appsettings.json file exists but empty, any call to clio apps generates **unhandled exception**

![image](https://user-images.githubusercontent.com/7285114/73153001-c75c8900-40da-11ea-801e-88921f86002a.png)

**Comment by vladimir-nikonov** [comment]
We added check this collision and get recomendation for correct this, but exception stack included in output stream

**Comment by kirillkrylov** [comment]
Thanks

Sincerely,
Kirill Krylov, CPA
