### ISSUE TITLE
error on clio update

### ISSUE THREAD

**Issue by kirillkrylov** [Advance-Technologies-Foundation/clio#115]
I am getting error when updating clio, this did not happen until last week

![image](https://user-images.githubusercontent.com/7285114/73154152-12789b00-40df-11ea-8c4d-467f05a752ef.png)

**Comment by vladimir-nikonov** [comment]
in release 2.0.0.3 dotnecore version has been updated on version 2.2 and you must reconfigure your local environment to netcoreapp2.2. We strongly recomended use Global CLI Tool for release 2.0.0.3 and higher for install and upgrade your cli version.
