### ISSUE TITLE
Update-cli error

### ISSUE THREAD

**Issue by IlyaChubko** [Advance-Technologies-Foundation/clio#119]
cli version 2.0.0.6
command: clio update-cli
![image](https://user-images.githubusercontent.com/6832799/74527748-8b794e80-4f37-11ea-992d-6a5dfab93e7e.png)

https://github.com/Advance-Technologies-Foundation/clio/releases/download/2.0.0.6/release_2.0.0.6.zip

**Comment by oleksandr-davydko** [comment]
It's no need in usage of updater in latest releases. We strongly recommend you to use .NET Core global CLI tools:
dotnet tool install clio -g
