### ISSUE TITLE
ignore-ssl not working

### ISSUE THREAD

**Issue by IlyaChubko** [Advance-Technologies-Foundation/clio#120]
Command "--ignore-ssl" is not working
clio version: 2.0.0.6
![image](https://user-images.githubusercontent.com/6832799/74527896-f165d600-4f37-11ea-9b27-b1a1e0d85bb6.png)

Site s working:
![image](https://user-images.githubusercontent.com/6832799/74528033-40ac0680-4f38-11ea-969c-eb943f1e0037.png)

**Comment by vladimir-nikonov** [comment]
this feature was not supported in the next versions (2.0.0.7 and higher). Work with untrusted SSL certificate will be supported by default
