### ISSUE TITLE
Generate-pkg-zip

### ISSUE THREAD

**Issue by IlyaChubko** [Advance-Technologies-Foundation/clio#121]
Добрый день!
Перестал работать метод generate-pkg-zip в новой версии.
Ошибка "The method or operation is not implemented"

**Comment by alexbondj** [comment]
у меня работал на 2.0.0.6

**Comment by IlyaChubko** [comment]
> у меня работал на 2.0.0.6

как работал, если в исходниках throw new NotImplementedException(); ?

**Comment by alexbondj** [comment]
Написал как есть. Я сам код команды не дебажил. Может метод уже не нужен

**Comment by IlyaChubko** [comment]
Как это не нужен? Он у меня активно в DevOps CI используется для сборки всех пакетов в один архив. В прошлых версия работал, а в новой просто остановил весь процесс.
Спасибо, что приняли merge.
