### ISSUE TITLE
Release 2.0.0.7

### ISSUE THREAD

**Issue by IlyaChubko** [Advance-Technologies-Foundation/clio#128]
Добрый день!
Коллеги, почему-то release сборка отличается от сборки исходного кода на текущий момент, хотя новых коммитов не было.

Слева сборка из исходных кодов, справа от release.
![image](https://user-images.githubusercontent.com/6832799/75012305-c1b45200-5492-11ea-962b-c7d343eebfce.png)
Прошу Вас исправить release сборку, так как там, например, --ignore-ssl обязательно необходим, а в исходниках уже необязателен.

**Comment by vladimir-nikonov** [comment]
Параметр --ignore-ssl уже не надо передавать, система работает без него корректно в различных режимах. По поводу различного размера, то тут могут быть отличия только в режиме сборки release или debug сборок + надо смотреть какая ветка исходного кода сейчас выкачана (мы перешли на систему master + develop)
