### ISSUE TITLE
Release 2.0.0.8 bug

### ISSUE THREAD

**Issue by IlyaChubko** [Advance-Technologies-Foundation/clio#133]
Добрый день!
В релизной сборке 2.0.0.8 баг сломался метод compress
![image](https://user-images.githubusercontent.com/6832799/76245069-4a314180-624c-11ea-9c63-bb7276240684.png)

**Comment by vladimir-nikonov** [comment]
Илья, только что проверил метод работает корректно. Можешь показать сигнатуру с которой ты его вызываешь?

**Comment by IlyaChubko** [comment]
> Илья, только что проверил метод работает корректно. Можешь показать сигнатуру с которой ты его вызываешь?

Не был реализован метод упаковки нескольких пакетов
Сигнатура:
generate-pkg-zip <директория> -p <список пакетов> -d <путь к архиву.zip>
