### ISSUE TITLE
Register environment with user name containing a space

### ISSUE THREAD

**Issue by RyanFarley** [Advance-Technologies-Foundation/clio#136]
I have an environment where the username has a space in it, such as "Firstname Lastname". I cannot seem to register an environment with a space in the user name on the command line. When I attempt to do so it only seems to use the Firstname as the username. I've tried enclosing the entire user name in quotes with the same result.

For example, the following commands:
clio reg-web-app <ENVIRONMENT_NAME> -u http://mysite.creatio.com -l "FIrst Last" -p password

Appears to attempt to register the environment with username of "First". For now, I've edited the json file manually to add the environment.

**Comment by vladimir-nikonov** [comment]
Hi @RyanFarley, what is you clio version?
![whitespaces_login](https://user-images.githubusercontent.com/26967647/76402732-7c49bd00-638c-11ea-8dc5-17fd13a1618d.gif)

**Comment by RyanFarley** [comment]
Hello @vladimir-nikonov, I am using 2.0.0.8, but I am using on a Mac, so maybe that is the difference?

![image](https://user-images.githubusercontent.com/106127/76444862-d1cc9c80-6381-11ea-9f6b-a0f7d9f83d05.png)

**Comment by RyanFarley** [comment]
Possibly there are other issues with quotes in command-lines on a Mac? Whenever I have to include quotes in the command-line I end up getting errors, for example:

![image](https://user-images.githubusercontent.com/106127/76450694-730c2080-638b-11ea-8ffb-d46be90c067c.png)

**Comment by oleksandr-davydko** [comment]
@RyanFarley I'll investigate this issue.
Btw, SQL script problem is not related to arguments parsing. Maybe your app is connected to postgresql db and you need to use another syntax to compose queries. But still, we have a known bug, related to postgresql: https://github.com/Advance-Technologies-Foundation/clio/issues/89.

**Comment by RyanFarley** [comment]
@oleksandr-davydko Thanks, I'll fork and test on my Mac as well.

For the SQL issue, as an FYI this is a SQL db, not postgresql.

**Comment by oleksandr-davydko** [comment]
@RyanFarley I've just succeeded in creating env by using single quotes:
<img width="573" alt="изображение" src="https://user-images.githubusercontent.com/14204345/76457885-41727400-63e2-11ea-99b8-7408539c1a88.png">

Tommorow I'm gonna look at sql script issue

**Comment by RyanFarley** [comment]
Ah, good to know, I didn't try the single quotes. Thanks.
