### ISSUE TITLE
SQL service command not working as expected

### ISSUE THREAD

**Issue by kirillkrylov** [Advance-Technologies-Foundation/clio#143]
PS C:\Users\k.krylov> ```dotnet tool update clio -g```
**Tool 'clio' was reinstalled with the latest stable version (version '2.0.0.8').**

PS C:\Users\k.krylov> ```clio packages -e cloud```

  Name                        Maintainer

  ActionsDashboard            Terrasoft
  Base                        Terrasoft
  Base_ENU                    Terrasoft
  BaseProcessDesigner         Terrasoft
  BaseScoring                 Terrasoft
  BpmonlineCloudIntegration   Terrasoft
  Calendar                    Terrasoft
  CalendarBase                Terrasoft
  CallMessagePublisher        Terrasoft
  ___cliogate                    Advanced Technologies Foundation___
  Completeness                Terrasoft
  ContentBuilder              Terrasoft
  CTIBase                     Terrasoft
  CTIVirtualProvider          Terrasoft
  Custom                      Customer
  DcmDesigner                 Terrasoft
  Deduplication               Terrasoft
  DesignerTools               Terrasoft
  EmailMessagePublisher       Terrasoft
  EmailMining                 Terrasoft
  EmailsSearch                Terrasoft
  EmailTemplate               Terrasoft
  Enrichment                  Terrasoft
  ESN                         Terrasoft
  Exchange                    Terrasoft
  ExchangeListener            Terrasoft
  ExternalAccess              Terrasoft
  FacebookIntegration         Terrasoft
  FastReport                  Terrasoft
  FastReportEngine            Terrasoft
  FileImport                  Terrasoft
  ForeignExchange             Customer
  GlobalSearch                Terrasoft
  GoogleTagManagerMeasurementsTerrasoft
  IntegrationV2               Terrasoft
  KnowledgeBase               Terrasoft
  LDAP                        Terrasoft
  LinkPreview                 Terrasoft
  Managers                    Terrasoft
  Message                     Terrasoft
  MessagePublisher            Terrasoft
  ML                          Terrasoft
  MLangContent                Terrasoft
  MLBase                      Terrasoft
  MLRegression                Terrasoft
  MLScoring                   Terrasoft
  Mobile                      Terrasoft
  MobileDesignerTools         Terrasoft
  NUI                         Terrasoft
  OAuth20Integration          Terrasoft
  OSM                         Terrasoft
  Platform                    Terrasoft
  ProcessDesigner             Terrasoft
  ProcessLibrary              Terrasoft
  ProductCore                 Terrasoft
  ProductCoreMessagePublishersTerrasoft
  Reports                     Terrasoft
  ServiceDesigner             Terrasoft
  SocialMessagePublisher      Terrasoft
  SocialNetworkIntegration    Terrasoft
  SSP                         Terrasoft
  SspKnowledgeBase            Terrasoft
  SspWorkplace                Terrasoft
  Studio                      Terrasoft
  TaskMessagePublisher        Terrasoft
  Timeline                    Terrasoft
  Translation                 Terrasoft
  TwitterIntegration          Terrasoft
  UIv2                        Terrasoft
  VisaNotification            Terrasoft
  WebForm                     Terrasoft
  WebitelCollaborations       Terrasoft
  WebitelCore                 Terrasoft
  Wizards                     Terrasoft
  Workplace                   Terrasoft

Find 75 packages in https://027353-studio.creatio.com/
PS C:\Users\k.krylov> ```clio execute-sql-script "SELECT Id FROM SysSettings WHERE Code = 'CustomPackageId'" -e cloud```
System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Creatio.Client.ATFWebRequestExtension.GetServiceResponse(HttpWebRequest request)
   at Clio.Common.SqlScriptExecutor.Execute(String sql, IApplicationClient applicationClient, EnvironmentSettings settings)
   at Clio.Command.SqlScriptCommand.SqlScriptCommand.Execute(ExecuteSqlScriptOptions opts)
PS C:\Users\k.krylov>

**Comment by fbuffa2003** [comment]
Same issue

Tool 'clio' was successfully updated from version '3.0.1.10' to version '3.0.1.17'.
PS C:\WINDOWS\system32> clio execute-sql-script "SELECT Id FROM SysSettings WHERE Code = 'CustomPackageId'" -e devsouthu
System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Creatio.Client.ATFWebRequestExtension.GetServiceResponse(HttpWebRequest request)
   at Creatio.Client.CreatioClient.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Common.CreatioClientAdapter.ExecutePostRequest(String url, String requestData, Int32 requestTimeout)
   at Clio.Common.SqlScriptExecutor.Execute(String sql, IApplicationClient applicationClient, EnvironmentSettings settings)
   at Clio.Command.SqlScriptCommand.SqlScriptCommand.Execute(ExecuteSqlScriptOptions opts)
PS C:\WINDOWS\system32>

**Comment by fbuffa2003** [comment]
![image](https://user-images.githubusercontent.com/26152219/182629521-37f50319-6179-4d0d-bed4-e954d9b10997.png)
This woks for me in Powershell
