### ISSUE TITLE
Build с ошибками clio 2.0.0.9

### ISSUE THREAD

**Issue by auralskaya** [Advance-Technologies-Foundation/clio#150]
Добрый день. Пытаемся собрать clio 2.0.0.9 с помощью build.psl. Просьба обратить внимание на результат выполнения строк п.2-п.3. 
У меня установлены dotnet начиная с версии 2.0, заканчивая версией 3.1, однако ошибка указывает на несовместимость. Та же самая ошибка, если dotnet чисто версии 2.2. Также возможно неправильно указан путь в п.2.

**1. dotnet build .\clio\clio.csproj -c Release --no-incremental**

Microsoft (R) Build Engine версии 16.5.0+d4cbfca49 для .NET Core
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Восстановление завершено в 29,65 ms для C:\Users\Alina\Desktop\3\clio-2.0.0.9\clio\clio.csproj.
  Восстановление завершено в 29,65 ms для C:\Users\Alina\Desktop\3\clio-2.0.0.9\updater\updater.csproj.
  updater -> C:\Users\Alina\Desktop\3\clio-2.0.0.9\updater\bin\Release\netcoreapp2.2\updater.dll
  clio -> C:\Users\Alina\Desktop\3\clio-2.0.0.9\clio\bin\Release\netcoreapp2.2\clio.dll
  Пакет "C:\Users\Alina\Desktop\3\clio-2.0.0.9\clio\bin\Release\clio.2.0.0.9.nupkg" успешно создан.

Сборка успешно завершена.
    Предупреждений: 0
    Ошибок: 0

Прошло времени 00:00:01.46

**2. dotnet build .\cliogate\cliogate.csproj -c Release -f netstandard2.2 --no-incremental
dotnet .\clio\bin\Release\netcoreapp2.2\clio.dll compress .\cliogate -d .\clio\cliogate\netcore\cliogate.gz
Get-ChildItem .\cliogate\Files\Bin | Remove-Item -Force**

Microsoft (R) Build Engine версии 16.5.0+d4cbfca49 для .NET Core
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Восстановление завершено в 28,95 ms для C:\Users\Alina\Desktop\3\clio-2.0.0.9\cliogate\cliogate.csproj.
C:\Program Files\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(149,5): **error NETSDK1045: текущий пакет SDK для .NET не поддерживает целевой объект .NET Standard 2.2. Выберите .NET Standard 2.1 или более раннюю версию либо используйте версию пакета SDK для .NET, которая поддерживает .NET Standard 2.2. [C:\Users\Alina\Desktop\3\clio-2.0.0.9\cliogate\cliogate.csproj]**

Ошибка сборки.

C:\Program Files\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(149,5): **error NETSDK1045: текущий пакет SDK для .NET не поддерживает целевой объект .NET Standard 2.2. Выберите .NET Standard 2.1 или более раннюю версию либо используйте версию пакета SDK для .NET, которая поддерживает .NET Standard 2.2.** [C:\Users\Alina\Desktop\3\clio-2.0.0.9\cliogate\cliogate.csproj]
    Предупреждений: 0
    Ошибок: 1

Прошло времени 00:00:00.17
**Could not find a part of the path 'C:\Users\Alina\Desktop\3\clio-2.0.0.9\clio\cliogate\netcore\cliogate.gz'.**

**3. dotnet build .\cliogate\cliogate.csproj -c Release -f net472 --no-incremental
dotnet .\clio\bin\Release\netcoreapp2.2\clio.dll compress .\cliogate -d .\clio\cliogate\netframework\cliogate.gz
Get-ChildItem .\cliogate\Files\Bin | Remove-Item -Force**

Microsoft (R) Build Engine версии 16.5.0+d4cbfca49 для .NET Core
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Восстановление завершено в 28,33 ms для C:\Users\Alina\Desktop\3\clio-2.0.0.9\cliogate\cliogate.csproj.
**C:\Program Files\dotnet\sdk\3.1.201\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3277: обнаружены неразрешимые конфликты между различными версиями "Terrasoft.UI.WebControls". Эти конфликты перечисляются в журнале сборки, если выбран подробный уровень детализации журнала. [C:\Users\Alina\Desktop\3\clio-2.0.0.9\cliogate\cliogate.csproj]**
  cliogate -> C:\Users\Alina\Desktop\3\clio-2.0.0.9\cliogate\Files\Bin\cliogate.dll

Сборка успешно завершена.

**C:\Program Files\dotnet\sdk\3.1.201\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3277: обнаружены неразрешимые конфликты между различными версиями "Terrasoft.UI.WebControls". Эти конфликты перечисляются в журнале сборки, если выбран подробный уровень детализации журнала. [C:\Users\Alina\Desktop\3\clio-2.0.0.9\cliogate\cliogate.csproj]**
    Предупреждений: 1
    Ошибок: 0

Прошло времени 00:00:00.43
Done

**4.  dotnet build .\clio\clio.csproj -c Debug --no-incremental**

Microsoft (R) Build Engine версии 16.5.0+d4cbfca49 для .NET Core
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Восстановление завершено в 32,13 ms для C:\Users\Alina\Desktop\3\clio-2.0.0.9\clio\clio.csproj.
  Восстановление завершено в 32,13 ms для C:\Users\Alina\Desktop\3\clio-2.0.0.9\updater\updater.csproj.
  updater -> C:\Users\Alina\Desktop\3\clio-2.0.0.9\updater\bin\Debug\netcoreapp2.2\updater.dll
  clio -> C:\Users\Alina\Desktop\3\clio-2.0.0.9\clio\bin\Debug\netcoreapp2.2\clio.dll
  Пакет "C:\Users\Alina\Desktop\3\clio-2.0.0.9\clio\bin\Debug\clio.2.0.0.9.nupkg" успешно создан.

Сборка успешно завершена.
    Предупреждений: 0
    Ошибок: 0

Прошло времени 00:00:01.48
Windows PowerShell
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

**Comment by vladimir-nikonov** [comment]
Добрый день, спасибо что обратили внимание, в рамках следующих релизов мы не планируем поддерживать такие скрипты и удалим из репозитория. Нашей команде бюло бы очень полезно узнать причины которые приводят к необходимости самостоятельной сборки clio.
