### ISSUE TITLE
Проблемы удаления пакета

### ISSUE THREAD

**Issue by IlyaChubko** [Advance-Technologies-Foundation/clio#152]
При выполнении операции delete-pkg-remote утилита отображает результат **Done**, хотя пакет не удален.
В конфигурации ошибка удаления, например, из-за того, что он был установлен с помощью раздела "Установка и удаление приложений"
![image](https://user-images.githubusercontent.com/6832799/83004773-bc7a1c80-a018-11ea-836d-38dadbaa61da.png)
![image](https://user-images.githubusercontent.com/6832799/83004912-e0d5f900-a018-11ea-81f6-84a75ae58159.png)

**Comment by vladimir-nikonov** [comment]
Эта ошибка связана с тем что flow работы с пакетами и приложениями, на данный момент не может быть смешан. Или работаем с приложениями, или с пакетами, текущая особенность платформы
