### ISSUE TITLE
При создании пакета чрез консоль и установке - ошибки, так же ошибки при выполнении install-gate

### ISSUE THREAD

**Issue by AlekseyNigreskul** [Advance-Technologies-Foundation/clio#167]
Здравствуйте! При создании пакета и установке через консоль наблюдаются ошибки:
https://prnt.sc/tv421l
Ошибки при выполнении команды install-gate - https://prnt.sc/tv42i0
Версия Creatio 7.16.2.1600 Развернута локально, включен режим разработки в ФС.

**Comment by fejdraus** [comment]
Проверил на нескольких средах - установка возможно через данную команду только на продуктах начиная с 7.17.0 версии
