### ISSUE TITLE
clio add-item model error

### ISSUE THREAD

**Issue by artem263** [Advance-Technologies-Foundation/clio#168]
Для сборки версии 7.16.2.1600 не получается создать модель с помощью команды clio add-item model
Команды clio add-item service, clio add-item entity-listener отрабатывают нормально. Прилагаю скрин.
https://priscree.ru/img/1b62fe40dd844c.png

**Comment by AlekseyNigreskul** [comment]
У меня такая же ситуация для версии 7.16.3.1473 - https://prnt.sc/ucuqux

**Comment by kirillkrylov** [comment]
![image](https://user-images.githubusercontent.com/7285114/96920403-c9127c00-14b5-11eb-8905-305028a65001.png)
