### ISSUE TITLE
Ошибки при конвертировании пакета + не выгружает пакет

### ISSUE THREAD

**Issue by AlekseyNigreskul** [Advance-Technologies-Foundation/clio#171]
При попытке выгрузить пакет загрузка не выполняется - https://prnt.sc/v0gtx8
Так же если выгрузить пакет в архив через интерфейс системы и выполнить конвертацию пакета а пакет-проект, то выдаются ошибки - https://prnt.sc/v0gvyu
 
Используется версия 2.0.0.9
Версия Creatio 7.16.4.1731

Какие изменения нужно внести, что бы отрабатывало корректно?
Благодарю.

**Comment by iwebcas** [comment]
Добрый день. 
При выгрузке пакета указывайте только имя пакета (без ".gz")
В случае, если хотите указать путь к файлу, в который выгружать, то нужно указывать "--DestinationPath" (-d).
По второму пункту, вероятнее всего вы находитесь не в том контексте (путь пакета, который пытается сконвертировать система, не существует)

**Comment by AlekseyNigreskul** [comment]
По поводу конвертации разобрался. а вот по поводу выгрузки нет.
Выгружаю - https://prnt.sc/v0jwsp
cliogate установлено - https://prnt.sc/v0jx5a

**Comment by AlekseyNigreskul** [comment]
и еще вопрос, какую версию clio устанавливать 2.0.0.9 или 2.0.0.12?
при выполнении команды dotnet tool install clio -g устанавливается 2.0.0.12, но когда начинаешь работать с утилитой то выводится сообщение, что есть версия 2.0.0.9 и просит сделать апдейт.

**Comment by vladimir-nikonov** [comment]
Использовать последнюю по номеру - 2.0.0.12, ошибку с проверкой обновления исправим в ближайшее время
