### ISSUE TITLE
Ошибка установки на сервере

### ISSUE THREAD

**Issue by okterij** [Advance-Technologies-Foundation/clio#173]
Коллеги, добрый день.
Пробую установить утилиту для работы с Creatio через консоль,  clio (взял последнуюю версию, 2.0.0.9)
Билд не проходит, выдает ошибку:
  Determining projects to restore...
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [F:\Distr\clio_2.0.0.9\clio\clio.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error :   An error occurred while sending the request. [F:\Distr\clio_2.0.0.9\clio\clio.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error :   The response ended prematurely. [F:\Distr\clio_2.0.0.9\clio\clio.csproj]
 
Build FAILED.
 
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [F:\Distr\clio_2.0.0.9\clio\clio.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error :   An error occurred while sending the request. [F:\Distr\clio_2.0.0.9\clio\clio.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error :   The response ended prematurely. [F:\Distr\clio_2.0.0.9\clio\clio.csproj]
    0 Warning(s)
    1 Error(s)
Сервер на ОС win 2016 r2
Установлен dotnet 3.1
Интернета на данном сервере нет, возможности подключить – так же нет

**Comment by fejdraus** [comment]
Установите через команду dotnet tool install clio -g и установится 2.0.0.12, она работает без ошибок с MSSQL, с PostgreSQL и Oracle есть ошибка при переводе всех пакетов издателя в режим разработки. А так вроде работает все

**Comment by okterij** [comment]
К сожалению, это не работает, иначе я бы не искал другие способы
Если не трогать файл NuGet.config, выдает такое сообщение:
![clio_err1](https://user-images.githubusercontent.com/15180374/97524847-bfb27380-19cf-11eb-9073-61dc5c99fe18.png)

    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\Users\User\AppData\Local\Temp\f3kpf0ss.bn4\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error :   Response status code does not indicate success: 407(Proxy Authorization Required). [C:\Users\User\AppData\Local\Temp\f3kpf0ss.bn4\restore.csproj]
    The tool package could not be restored.
    Tool 'clio' failed to install. This failure may have been caused by:

    * You are attempting to install a preview release and did not use the --version option to specify the version.
    * A package by this name was found, but it was not a .NET Core tool.
    * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
    * You mistyped the name of the tool.

    For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

Если в файле NuGet.config (в C:\Users\User\AppData\Roaming\NuGet) добавить строку 
`<add key="local" value="F:/Distr/Clio_2.0.0.9" />`
то ошибка меняется:
![clio_err2](https://user-images.githubusercontent.com/15180374/97524940-ea043100-19cf-11eb-8f87-78be38cc2027.png)

    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\cliogate' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Command' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Common' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Environment' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\help' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Package' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Project' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Properties' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\tools' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\tpl' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Utilities' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\WebApplication' contains an invalid version. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error :   Response status code does not indicate success: 407 (Proxy Authorization Required). [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
    The tool package could not be restored.
    Tool 'clio' failed to install. This failure may have been caused by:

    * You are attempting to install a preview release and did not use the --version option to specify the version.
    * A package by this name was found, but it was not a .NET Core tool.
    * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
    * You mistyped the name of the tool.

    For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool`

**Comment by fejdraus** [comment]
У Вас случайно VPN или proxy не включен?

**Comment by okterij** [comment]
Проверил, да, в IE был включен прокси, при выключении ушли строки:
```
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error :   Response status code does not indicate success: 407 (Proxy Authorization Required). [C:\Users\User\AppData\Local\Temp\15jghpx2.xt3\restore.csproj]
```
но основная часть осталась:
```
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\cliogate' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Command' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Common' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Environment' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\help' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Package' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Project' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Properties' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\tools' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\tpl' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\Utilities' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): warning : The folder 'F:\Distr\Clio_2.0.0.9\clio\WebApplication' contains an invalid version. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error :   An error occurred while sending the request. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error :   The response ended prematurely. [C:\Users\User\AppData\Local\Temp\tf5y0tky.mjb\restore.csproj]
The tool package could not be restored.
Tool 'clio' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

**Comment by fejdraus** [comment]
Попробуйте теперь поставить 2.0.0.12

**Comment by okterij** [comment]
А где его взять? я скачал последний релиз по [ссылке](https://github.com/Advance-Technologies-Foundation/clio/releases)
2.0.0.12 там нет

**Comment by fejdraus** [comment]
Написано что подключение к NuGet. Пробовали создавать просто проект какой-то для .net core типа dotnet new console ?

**Comment by okterij** [comment]
я в этом особо не разбираюсь, т.е. я скачал релиз, перенес на сервер, установил туда дотнет и выполнил инсталл по инструкции, получил ошибку.
дальше пошел искать как поставить из локальных файлов, нашел инфо про строку в NuGet.config - не помогло, пошел сюда.
Что-либо создавать не пробовал.
Мне по факту консоль нужна для автоматизации процессса поставки, каких-либо средств разработки на сервере не установлено

**Comment by okterij** [comment]
**upd.**
Закомментировал строку в NuGet.config файле
`<add key="local" value="F:/Distr/Clio_2.0.0.9" />`
После чего дотнет корректно выполнил команду регистрации.
Очень странно все, потому что ДО настройки прокси в IE, эта команда не отрабатывала, возможно сам факт проставленного прокси срабатывал как триггер и была попытка доступа в интернет

**Comment by fejdraus** [comment]
Теперь работает все?

**Comment by okterij** [comment]
В текущем профиле функционал заработал, однако на новом профиле успех установки повторить не удалось.

**Comment by fejdraus** [comment]
думаю тут вопрос именно по .net core, попробуйте создать проект на нем минимальные и поработать с NuGet

**Comment by fejdraus** [comment]
может для Вашей задачи стоит использовать стандартный WorkspaceConsole из дистрибутива?

**Comment by okterij** [comment]
По задумке планируется либо собирать исходный код в пакеты на сервере и устанавливать его в автоматическом режиме, либо загружать из файловой системы.
+ версия системы 7.14.4, есть ли там консоль?

**Comment by fejdraus** [comment]
Консоль есть во всех версиях .Net Framework версии, на .Net Core не смотрел
