### ISSUE TITLE
Idle console output after install package

### ISSUE THREAD

**Issue by IlyaChubko** [Advance-Technologies-Foundation/clio#179]
![image](https://user-images.githubusercontent.com/6832799/105454844-a39f3500-5c93-11eb-80bd-eff19b4e013b.png)

**Comment by vitaliipasko** [comment]
I have the same error from time to time
![image](https://user-images.githubusercontent.com/12555719/137697001-a180a5d9-5f94-4a0a-aadf-8bc59960e3e1.png)
