### ISSUE TITLE
Error on Clio push-pkg / install

### ISSUE THREAD

**Issue by Pratik-Sanghani** [Advance-Technologies-Foundation/clio#189]
Hi,

I was trying to install the package in a cloud instance. but I am getting errors every time on uploading the package itself.
This is the SS of the error.
![image](https://user-images.githubusercontent.com/25661686/125830768-26d081e8-442b-42e9-94c8-7513aa8005c6.png)

Can anyone guide me on what could cause this issue and how to resolve it?
 
Thanks in Advance. :-)

**Comment by Pratik-Sanghani** [comment]
I also had tried to push in another Cloud Instance. There Package was installed successfully.

**Comment by IlyaChubko** [comment]
Hi! You typed install command without environment, may be active environment is empty
Can you try:
1) Check "ActiveEnvironmentKey" in json with command **clio show-web-app-list**
2) Try install the package with full command
**clio install package.gz -u http://localhost:8080 -l Supervisor -p Supervisor**

**Comment by Pratik-Sanghani** [comment]
Thanks for the suggestion, I had tried this way as well but no luck. I am encountering the same Error.

**Comment by IlyaChubko** [comment]
> Thanks for the suggestion, I had tried this way as well but no luck. I am encountering the same Error.

Creatio is Linux version?
If yes, you have to add -i true argument

**Comment by Pratik-Sanghani** [comment]
No, it is not working as well. The destination version is lower (7.17.1.1363) than the source instance version (7.17.3.1377). 
Is there any chance that this could be the reason for the error?

**Comment by TheEmperor80** [comment]
@Pratik-Sanghani Did you manage to get around this? We have the very same problem! Thanks, Robert
