### ISSUE TITLE
ping command doesn't work on .Net Core/macOS

### ISSUE THREAD

**Issue by muhammetari** [Advance-Technologies-Foundation/clio#197]
clio version clio 3.0.1.6

<img width="836" alt="image" src="https://user-images.githubusercontent.com/22047375/168432464-cbc0e51d-8572-4036-9385-2e32c7bbb8d0.png">

**Comment by iwebcas** [comment]
clio version 3.0.1.6

[cid:76135e56-3de3-4ec9-a812-b565997c73e6]
________________________________
From: muhammetari ***@***.***>
Sent: Saturday, May 14, 2022 18:09
To: Advance-Technologies-Foundation/clio ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Advance-Technologies-Foundation/clio] ping command doesn't work on .Net Core/macOS (Issue #197)


clio version clio 3.0.1.6

[image]<https://user-images.githubusercontent.com/22047375/168432464-cbc0e51d-8572-4036-9385-2e32c7bbb8d0.png>

**Comment by iwebcas** [comment]
On config file appsettings.json
In your current environment, you need to set the following parameter:
IsNetCore: true,

**Comment by iwebcas** [comment]
Thank you. Let's look at this problem.

**Comment by iwebcas** [comment]
Hello. We fixed this bug on version 3.0.1.8
