### ISSUE TITLE
Generate SDK based (and netstandard 2.0) c# projects with new-pkg command

### ISSUE THREAD

**Issue by vadimart92** [Advance-Technologies-Foundation/clio#224]
`new-pkg ` command generates csproj file in old style: `<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">` which is obsolete and hard to support. It would be better to use SDK style projects.  
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by kirillkrylov** [comment]
@vadimart92 use `clio ap pkn_name` instead
See [add-package](https://github.com/Advance-Technologies-Foundation/clio/blob/master/clio/Command/AddPackageCommand.cs) command

**Comment by vadimart92** [comment]
@kirillkrylov thanks, maybe it's better to mention this command here https://github.com/Advance-Technologies-Foundation/clio#creating-new-package
