### ISSUE TITLE
how to handle ascents in clio? 

### ISSUE THREAD

**Issue by fbuffa2003** [Advance-Technologies-Foundation/clio#227]
Hello guys, I have a issue with the ascents in clio. In the console my query looks nice but in Creatio is with a ?

![script](https://user-images.githubusercontent.com/26152219/233748780-3b67b6ac-9925-4f1c-90a9-fff473eb99e4.png)
![InCreatio](https://user-images.githubusercontent.com/26152219/233748784-4100cd46-9f45-4ba1-9722-3a0fd15ebeb6.png)
[HereMyFile.zip](https://github.com/Advance-Technologies-Foundation/clio/files/11299773/HereMyFile.zip)

**Comment by fbuffa2003** [comment]
Btw is working fine from VSC extension. Only in the console and powershell using the command happened.

**Comment by fbuffa2003** [comment]
I did some test with the webserivce and seams to be adding the encoding in the content-type works.

![test2](https://user-images.githubusercontent.com/26152219/233840350-148178a8-d5d9-4ac6-92c4-5d7d39c68c56.png)
![test3](https://user-images.githubusercontent.com/26152219/233840435-7d5400c2-a197-4300-8e34-028e8b673ab7.png)

Perhaps this helps.

**Comment by kirillkrylov** [comment]
Please check the latest update where this issue was fixed, and close the bug
