### ISSUE TITLE
Clio Creatio Install MSSQL remote DB

### ISSUE THREAD

**Issue by jcollazoMeritus** [Advance-Technologies-Foundation/clio#230]
Hi, is it possible to configure Clio to install MSSQL version and installing de db in a remote server?

Looking forward to you comments. 

Best regards,
-- 
Javier Collazo
jcollazo@mbsol.net
Company: (908) 200-2300 Ext. 223 | Direct: (908) 200-2348

**Comment by kirillkrylov** [comment]
Could you please elaborate a bit more. What exactly would you like Clio to do ?

**Comment by jcollazoMeritus** [comment]
Hi Kirill, I don't know if you remember, but I talked to you in the conference about Clio, after you last presentation :) You told me that if I had any questions I should use github, so here I am. What I want Clio to do is to install Creatio in our local server, as you do in the tutorial video. But I need the MSSQL version of Creatio and the database should be in a remote server. Is this possible or should i install Creatio manually?

**Comment by kirillkrylov** [comment]
I'll get it done in the next two weeks.

**Comment by vladimir-nikonov** [comment]
Hi @jcollazoMeritus. We aren`t planning to support such mode. Alternativly you can check our solution for automatic deployment, and you can use shared k8s cluster for use common server resources. Detailed see this [chapter](https://github.com/Advance-Technologies-Foundation/clio#installation-of-creatio-using-clio)
