### ISSUE TITLE
Issue running clio on Mac M2 with Netcode 6

### ISSUE THREAD

**Issue by fbuffa2003** [Advance-Technologies-Foundation/clio#241]
Hi Team, We are facing an issue installing clio on a Mac M2 chip, dotnet is installed correctly, but after doing "dotnet run clio" under the folder from the releases nothing happens, and the process stays there until is killed. If I run dotnet run clio --no-build then I got the message attached. Please feel free to contact me if some test need to do.
![image](https://github.com/Advance-Technologies-Foundation/clio/assets/26152219/98cf57c9-4f19-459a-950f-895ee40c8199)
![image](https://github.com/Advance-Technologies-Foundation/clio/assets/26152219/c24b365f-9cda-4631-ac4f-f48fe0869479)

Thanks,

**Comment by kirillkrylov** [comment]
[you can use the latest release](https://github.com/Advance-Technologies-Foundation/clio/releases/latest)
