### ISSUE TITLE
App bundle installation

### ISSUE THREAD

**Issue by o-serhiichyk** [Advance-Technologies-Foundation/clio#245]
Hi,
There is a problem with installing of apps and packages.

Clio, unlike Application Hub, doesn't support multiple app descriptor files in a single ZIP-archive (app bundles).

There are new backup endpoints (CreatePackageBackup, RestorePackageFromBackup) in Creatio that were implemented more than year ago. Only these new endpoints support app bundles and should be used instead of old ones during app/package installation.

**Comment by Mantikor123** [comment]
Hello, we also encountered the same problem and wanted to create a new issue, but we’ll just add it here.
I will not describe in detail, if there is any additional information on the portal (success.creatio.com) please contact SR-01251531
