### ISSUE TITLE
Can't create workspace in cloned repository

### ISSUE THREAD

**Issue by DimaK3000** [Advance-Technologies-Foundation/clio#246]
1) Clone empty repository 
`git clone https://git.com/repo`

3) Move to repo folder

2) Create workspace
`clio createw`

4) Result
`This operation requires empty folder!`

The workspace was not been created as folder not empty. The '.git' does not allow the creation of a new workspace.

**Comment by kirillkrylov** [comment]
Clio requires empty directory to create a workspace 

Try this instead.
```bash
clio createw
git init --initial-branch=master
git submodule add https://git.com/repo repo
```

Consider using [sparse-checkout](https://git-scm.com/docs/git-sparse-checkout)

**Comment by kirillkrylov** [comment]
@DimaK3000 
Starting with ver 6.0.2.21 `createw` command will try to create a workspace in an existing directory.
