### ISSUE TITLE
Add better error message when an App does not exists

### ISSUE THREAD

**Issue by kirillkrylov** [Advance-Technologies-Foundation/clio#254]
When using uninstall-app-remote command on an environment that does not contain an app to uninstall, clio returns a message that does not clearly identify a reason for failure.

![image](https://github.com/Advance-Technologies-Foundation/clio/assets/7285114/2f8cd953-63c8-40a3-8a85-f916475a56eb)

**Comment by vladimir-nikonov** [comment]
fixed in 6.0.2.42
