### ISSUE TITLE
Error compile-configuration after update clio to actial 

### ISSUE THREAD

**Issue by Mantikor123** [Advance-Technologies-Foundation/clio#264]
After updating Clio, we encountered a problem that the CI/CD in the compile-configuration command was broken
We also tried to do it explicitly on the server and also caught the error... what changed? what needs to be fixed to revive the already implemented logic

![Screenshot_1](https://github.com/Advance-Technologies-Foundation/clio/assets/24190423/fc5d9c92-5d86-47c5-a140-6af585bb137c)

**Comment by kirillkrylov** [comment]
@Mantikor123 
This error may occur when the environment name passed as an argument to clio is different from the registered environment name. This may happen when letter 'o' or 'e' or 'p' used in ukr instead of english.

**Comment by Mantikor123** [comment]
@kirillkrylov I'll check again, but the error occurred after the update. we updated from 6.0.2.19 to 6.0.2.45
With this everything worked, and there was no such error
![Screenshot_3](https://github.com/Advance-Technologies-Foundation/clio/assets/24190423/7a389ee9-2d55-4511-8011-0e449ec562b2)
