### ISSUE TITLE
Flush Redis icon

### ISSUE THREAD

**Issue by EugeneSparrow** [Advance-Technologies-Foundation/clio#269]
Hi team,

I noticed that maybe there was a wrong icon when run the flush Redis action.
After successful execution, I receive the following message:
![image](https://github.com/Advance-Technologies-Foundation/clio/assets/164352728/49e196aa-fcc9-4be1-adb9-e964a5a98c62)

From the text, I understand that the action was completed successfully. However, the icon shows the error.

**Comment by kirillkrylov** [comment]
@EugeneSparrow 
Fixed in Explorer v2.0.60
