### ISSUE TITLE
Provide a posibility to set custom TEMP folder

### ISSUE THREAD

**Issue by ogilievyi** [Advance-Technologies-Foundation/clio#275]
Due to security settings, the default temp folder can be unavailable
Please provide an opportunity to set custom path to the TEMP dir for the env

![image](https://github.com/Advance-Technologies-Foundation/clio/assets/137776567/1a881abe-d762-40b0-8500-eafd5d8b1155)

**Comment by kirillkrylov** [comment]
Added in 6.0.1.6
set CLIO_WORKING_DIRECTORY environment variable
See https://github.com/Advance-Technologies-Foundation/clio/commit/20b530c62f9e5f0bb68b3a5fcd5ab5bf989eef6d
