### ISSUE TITLE
Last version check compares versions incorrectly

### ISSUE THREAD

**Issue by o-serhiichyk** [Advance-Technologies-Foundation/clio#293]
With `"Autoupdate": true`, I'me getting "You should consider upgrading" message when installed version of the clio is **above** the last release on GitHub.

This is probably heppening because the last version published on NuGet is newer, than the one published on GitHub, but the condition in the source code is `currentVersion != latestVersion` (where `latestVersion` is taken from GitHub).

**Comment by vladimir-nikonov** [comment]
Fix in version 6.1.0.16+
