### ISSUE TITLE
Install Packages failed - clio push-pkg /packages/gz/Packages.zip

### ISSUE THREAD

**Issue by ChengLei14** [Advance-Technologies-Foundation/clio#311]
Good day and I would like to seek for advice and assistance here, got to see the relative error in issue - https://github.com/Advance-Technologies-Foundation/clio/issues/189, would like to ask for advice and solution to proceed move changes via GitHub.

Error out during the below code ran.

clio push-pkg /packages/gz/Packages.zip -l _<username>_ -p <password> -u <url>

Attached the screenshot of error log.
<img width="605" alt="ErrorLog" src="https://github.com/user-attachments/assets/115a5de7-8bd1-4c2c-9f87-19effc8bcc81">

**Comment by sbcproject** [comment]
having the same issue, what is the resolution on this?

**Comment by sbcproject** [comment]
> having the same issue, what is the resolution on this?

ok the reason was wrong password. never mind
