### ISSUE TITLE
Access denied with "clio new-pkg TestPackage -r bin"

### ISSUE THREAD

**Issue by simplecov** [Advance-Technologies-Foundation/clio#321]
Hi. I have a problem creating a project-package using
**clio new-pkg TestPackage -r bin**
Error
**System.UnauthorizedAccessException: Access to the path 'root_directory\Terrasoft.WebApp\Terrasoft.Configuration\Pkg\TestPackage' is denied.**
Location while command executing is
**root_directory\Terrasoft.WebApp\Terrasoft.Configuration\Pkg**

Windows 10. Powershell or cmd in administrative mode.
IIS also have full access to creatio directory with inheritance to all subfolders (not shure iis is on duty in this case)
clio version is 6.1.0.39 (latest, for now). Installed globally.

Command **clio new-pkg TestPackage** (without -r) worked fine but useless because i need to set reference on local core assembly.
And i need reference because alot of version conflicts in Terrasoft.Core namespace.

Appreciate any help.

**Comment by kirillkrylov** [comment]
This command is meant to run from workspace. Please see open-test project bat file in tasks directory. 

This command is not meant to used without workspace.

**Comment by simplecov** [comment]
Thx for answer. Where tasks directory is located? I'm not sure, where i need to find it.

**Comment by simplecov** [comment]
> This command is meant to run from workspace. Please see open-test project bat file in tasks directory.
> 
> This command is not meant to used without workspace.

Thx for answer. Where tasks directory is located? I'm not sure, where i need to find it.

**Comment by kirillkrylov** [comment]
@simplecov 
![image](https://github.com/user-attachments/assets/46d17c29-87c9-42ce-87aa-87a583aded0f)

**Comment by simplecov** [comment]
Sorry, im totally misunderstanding. Just more questions about how .cmd files are related to the topic of my issue.
I need to create workplace using clio and then use "new-pkg" with -r parameter?
What i need to set in -r parameter?

Appreciate for help.
