### ISSUE TITLE
show TimeStamp switch

### ISSUE THREAD

**Issue by ypolhun** [Advance-Technologies-Foundation/clio#323]
Hi

It would be great to have a key to display the timestamp of the command execution (for example  -st (Show TimeStamp)).

For example, I often do clio restart -u http://localhost:99/
but I would like to see when I last did it.

Thank you.

**Comment by vladimir-nikonov** [comment]
flag --ts was added to the 8.0.1.1 version to all command

**Comment by ypolhun** [comment]
Nice. Thank you.
