### ISSUE TITLE
Создание файла .sln для нового пакета

### ISSUE THREAD

**Issue by teamkiller7112** [Advance-Technologies-Foundation/clio#67]
Сейчас создается пакет с файлом проекта (.csproj) при открытии в VS нужно отдельно сохранять файл решения.

Нужно добавить создание файла .sln

**Comment by IlyaChubko** [comment]
Я здесь не соглашусь. У нас решение sln может собирать несколько проектов в пакетах

**Comment by teamkiller7112** [comment]
При начальном создании пакета у нас только один проект. Мы его в любом случае создаем, после того как открывает csproj.Потом можно спокойно добавлять новые проекты в sln.

**Comment by IlyaChubko** [comment]
Нет, когда у нас уже есть 5 проектов, то при создании нового пакета нам в этом новом пакете не нужно sln, только csproj, чтобы добавить его к существующему решению.
Смысла создавать еще одно решение нет!

**Comment by teamkiller7112** [comment]
Хм, а что если нам повесить на флаг? Например добавить параметр в команду, который создаст sln. 
`bpmcli new-pkg <PACKAGE_NAME> -sln`

Так по умолчанию пакет будет без файла решения, но те кому он нужен, могут указать дополнительный флаг.

**Comment by oleksandr-davydko** [comment]
https://github.com/Advance-Technologies-Foundation/clio/issues/108
Closed as a duplicate
