### ISSUE TITLE
Ошибка bpmcli convert

### ISSUE THREAD

**Issue by sergeytkachenko** [Advance-Technologies-Foundation/clio#69]
Выкачал себе пакет из развернутой сборки. 
Пытаюсь конвертировать в проект - получаю ошибку.
Не понимаю что делаю не правильно. 
Помогите пожалуйста. 

```
bpmcli pull-package Deduplication -u http://siteurl -l user -p password
bpmcli convert -p C:\Users\s.tkachenko\ Deduplication

Start converting package 'Deduplication'.
Created backup package 'Deduplication'.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at bpmcli.PackageConverter.GetPathFromEnvironment()
   at bpmcli.PackageConverter.GetTplPath(String tplPath)
   at bpmcli.PackageConverter.CreateProjectInfo(String path, String name, List`1 fileNames)
   at bpmcli.PackageConverter.ConvertPackage(ConvertOptions options)
```

**Comment by AlexanderMykulych** [comment]
> Выкачал себе пакет из развернутой сборки.
> Пытаюсь конвертировать в проект - получаю ошибку.
> Не понимаю что делаю не правильно.
> Помогите пожалуйста.
> 
> ```
> bpmcli pull-package Deduplication -u http://siteurl -l user -p password
> bpmcli convert -p C:\Users\s.tkachenko\ Deduplication
> 
> Start converting package 'Deduplication'.
> Created backup package 'Deduplication'.
> System.InvalidOperationException: Sequence contains no matching element
>    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
>    at bpmcli.PackageConverter.GetPathFromEnvironment()
>    at bpmcli.PackageConverter.GetTplPath(String tplPath)
>    at bpmcli.PackageConverter.CreateProjectInfo(String path, String name, List`1 fileNames)
>    at bpmcli.PackageConverter.ConvertPackage(ConvertOptions options)
> ```

Тоже словил эту ошибку.
Метод GetPathFromEnvironment в системной переменной PATH ищет путь, в котором есть "bpmcli", не находит и падает.
В моем случае bpmcli лежит по пути "C:\Users\user\Downloads\release_1.2.0.0", чтобы убрать ошибку я скопировал "*\release_1.2.0.0\" в "C:\Users\A.Mykulych\Downloads\bpmcli-release\" и добавил новый путь в PATH.

**Comment by alexd739** [comment]
Коллеги, внес исправления, в следующем релизе можно будет убрать workaround с именем папки
