### ISSUE TITLE
Проверить механизм Global CLI Tools и попробовать удалить команды update и register

### ISSUE THREAD

**Issue by vladimir-nikonov** [Advance-Technologies-Foundation/clio#75]
описание утилиты тут
https://habr.com/ru/post/359006/

**Comment by LiliaUst** [comment]
[Глобальные средства .NET Core - .NET Core CLI | Microsoft Docs](https://docs.microsoft.com/ru-ru/dotnet/core/tools/global-tools)
Создание глобального средства .NET Core с помощью интерфейса командной строки .NET Core(https://docs.microsoft.com/ru-ru/dotnet/core/tools/global-tools-how-to-create)
