### ISSUE TITLE
Добавить help по новым командам в Readme файл. Проверить работу execute-sql с СУБД PosgreSQL

### ISSUE THREAD

**Issue by vladimir-nikonov** [Advance-Technologies-Foundation/clio#87]

**Comment by LiliaUst** [comment]
Проверила работу операции execute-sql на PostgreSql. Если запрос написать напрямую в командной строке с использованием двойных кавычек, то запрос не выполняется. Работает только если запрос разместить в файле и экранировать все двойные кавычки обратным слешом.

**Comment by LiliaUst** [comment]
Для команды pull-pkg добавила в описание версию, с которой она поддерживается.
Добавила описание команды execute-sql-script.
