### ISSUE TITLE
execute-sql-script not working, if query contains double-quote (") symbol

### ISSUE THREAD

**Issue by LiliaUst** [Advance-Technologies-Foundation/clio#89]
При выполнении sql запроса операцией execute-sql-script, если текст запроса задается непосредственно в командной строке и в запросе есть символ ", то запрос по факту не выполняется, но и ошибку не показывает, просто в качестве результата выдает Done. Экранирование символов " не помогает.
Это критично для запросов к PostgreSql и Oracle (названия таблиц в ").
Также при выполнении запроса, который находится в файле, приходится все " экранировать, что крайне неудобно.
Для PostgreSql эта операция работает нормально только, если запрос находится в файле и все " экранированы обратным слешом.

**Comment by kirillkrylov** [comment]
С переходом облака на PostgreSQL, эта ошибка стала **критичной** !!!

![image](https://user-images.githubusercontent.com/7285114/78499427-516b4280-7759-11ea-9004-9a5e364160ea.png)

**Comment by oleksandr-davydko** [comment]
@kirillkrylov отвечу на английском, на случай если ещё кому-то понадобится.
There is a workaround for this issue: just use command without using script parameter (clio sql -e cloud). Then clio will prompt you for script and you'll have possibility to type in double qoute symbols without experiencing any problems.

**Comment by kirillkrylov** [comment]
@oleksandr-davydko How exactly do I type in my SQL ?

![image](https://user-images.githubusercontent.com/7285114/78503619-728b5d80-7770-11ea-9e99-cac04e38471f.png)

**Comment by oleksandr-davydko** [comment]
@kirillkrylov you should wrap column names and schema in double quotes too

**Comment by kirillkrylov** [comment]
did not help

![image](https://user-images.githubusercontent.com/7285114/78504161-f3982400-7773-11ea-8a03-6a4ae3c3f5be.png)

neither approach has helped

![image](https://user-images.githubusercontent.com/7285114/78504133-c2b7ef00-7773-11ea-992e-b18297a03cbc.png)

**Comment by oleksandr-davydko** [comment]
Unfortunetaly, workaround really not working now. I made some corretions to code, so in 2.0.0.9 it should work.

**Comment by kirillkrylov** [comment]
In 2.0.0.9 workaround works, query from file works, however inline does not. How does one escape double quotes ?

![image](https://user-images.githubusercontent.com/7285114/78815567-20994080-79d9-11ea-890d-a5b4a34fedee.png)

**Comment by oleksandr-davydko** [comment]
I'm afraid, that there is no way doing that due to problems in internal command-line args parser. Is that critical?
